export const TEAM_NAME_SV: Record<string, string> = {
  Algeria: 'Algeriet',
  Argentina: 'Argentina',
  Australia: 'Australien',
  Austria: 'Österrike',
  Belgium: 'Belgien',
  'Bosnia & Herzegovina': 'Bosnien-Hercegovina',
  Brazil: 'Brasilien',
  Canada: 'Kanada',
  'Cabo Verde': 'Kap Verde',
  Colombia: 'Colombia',
  'Congo DR': 'Kongo-Kinshasa',
  Croatia: 'Kroatien',
  Curaçao: 'Curaçao',
  Czechia: 'Tjeckien',
  Ecuador: 'Ecuador',
  Egypt: 'Egypten',
  England: 'England',
  France: 'Frankrike',
  Germany: 'Tyskland',
  Ghana: 'Ghana',
  Haiti: 'Haiti',
  'IR Iran': 'Iran',
  Iran: 'Iran',
  Iraq: 'Irak',
  Japan: 'Japan',
  Jordan: 'Jordanien',
  'Korea Republic': 'Sydkorea',
  Mexico: 'Mexiko',
  Morocco: 'Marocko',
  Netherlands: 'Nederländerna',
  'New Zealand': 'Nya Zeeland',
  Norway: 'Norge',
  Panama: 'Panama',
  Paraguay: 'Paraguay',
  Portugal: 'Portugal',
  Qatar: 'Qatar',
  'Saudi Arabia': 'Saudiarabien',
  Scotland: 'Skottland',
  Senegal: 'Senegal',
  'South Africa': 'Sydafrika',
  Spain: 'Spanien',
  Sweden: 'Sverige',
  Switzerland: 'Schweiz',
  Tunisia: 'Tunisien',
  Türkiye: 'Turkiet',
  Turkey: 'Turkiet',
  Uruguay: 'Uruguay',
  Uzbekistan: 'Uzbekistan',
  'United States': 'USA',
  USA: 'USA',
  "Côte d'Ivoire": 'Elfenbenskusten',
}

export function teamNameSv(name: string): string {
  return TEAM_NAME_SV[name] ?? name
}
