-- Swedish display names for VM nations already stored in vmt_matches.
-- Safe to run more than once.

update public.vmt_matches
set home_team = case home_team
  when 'Algeria' then 'Algeriet'
  when 'Australia' then 'Australien'
  when 'Austria' then 'Österrike'
  when 'Bosnia & Herzegovina' then 'Bosnien-Hercegovina'
  when 'Brazil' then 'Brasilien'
  when 'Canada' then 'Kanada'
  when 'Cabo Verde' then 'Kap Verde'
  when 'Congo DR' then 'Kongo-Kinshasa'
  when 'Croatia' then 'Kroatien'
  when 'Czechia' then 'Tjeckien'
  when 'Egypt' then 'Egypten'
  when 'France' then 'Frankrike'
  when 'Germany' then 'Tyskland'
  when 'IR Iran' then 'Iran'
  when 'Iran' then 'Iran'
  when 'Iraq' then 'Irak'
  when 'Jordan' then 'Jordanien'
  when 'Korea Republic' then 'Sydkorea'
  when 'Mexico' then 'Mexiko'
  when 'Morocco' then 'Marocko'
  when 'Netherlands' then 'Nederländerna'
  when 'New Zealand' then 'Nya Zeeland'
  when 'Norway' then 'Norge'
  when 'Portugal' then 'Portugal'
  when 'Saudi Arabia' then 'Saudiarabien'
  when 'Scotland' then 'Skottland'
  when 'Senegal' then 'Senegal'
  when 'South Africa' then 'Sydafrika'
  when 'Spain' then 'Spanien'
  when 'Sweden' then 'Sverige'
  when 'Switzerland' then 'Schweiz'
  when 'Tunisia' then 'Tunisien'
  when 'Türkiye' then 'Turkiet'
  when 'Turkey' then 'Turkiet'
  when 'United States' then 'USA'
  when 'Côte d''Ivoire' then 'Elfenbenskusten'
  else home_team
end,
away_team = case away_team
  when 'Algeria' then 'Algeriet'
  when 'Australia' then 'Australien'
  when 'Austria' then 'Österrike'
  when 'Bosnia & Herzegovina' then 'Bosnien-Hercegovina'
  when 'Brazil' then 'Brasilien'
  when 'Canada' then 'Kanada'
  when 'Cabo Verde' then 'Kap Verde'
  when 'Congo DR' then 'Kongo-Kinshasa'
  when 'Croatia' then 'Kroatien'
  when 'Czechia' then 'Tjeckien'
  when 'Egypt' then 'Egypten'
  when 'France' then 'Frankrike'
  when 'Germany' then 'Tyskland'
  when 'IR Iran' then 'Iran'
  when 'Iran' then 'Iran'
  when 'Iraq' then 'Irak'
  when 'Jordan' then 'Jordanien'
  when 'Korea Republic' then 'Sydkorea'
  when 'Mexico' then 'Mexiko'
  when 'Morocco' then 'Marocko'
  when 'Netherlands' then 'Nederländerna'
  when 'New Zealand' then 'Nya Zeeland'
  when 'Norway' then 'Norge'
  when 'Portugal' then 'Portugal'
  when 'Saudi Arabia' then 'Saudiarabien'
  when 'Scotland' then 'Skottland'
  when 'Senegal' then 'Senegal'
  when 'South Africa' then 'Sydafrika'
  when 'Spain' then 'Spanien'
  when 'Sweden' then 'Sverige'
  when 'Switzerland' then 'Schweiz'
  when 'Tunisia' then 'Tunisien'
  when 'Türkiye' then 'Turkiet'
  when 'Turkey' then 'Turkiet'
  when 'United States' then 'USA'
  when 'Côte d''Ivoire' then 'Elfenbenskusten'
  else away_team
end;
